# Generated by Django 4.2.2 on 2023-06-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
