# Generated by Django 4.2.2 on 2023-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_profile_img_alter_home_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about',
            field=models.CharField(default='text', max_length=500),
            preserve_default=False,
        ),
    ]
