# Generated by Django 4.2.2 on 2023-06-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link_code',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
