# Generated by Django 4.2.2 on 2023-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_link_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
