# Generated by Django 4.2.2 on 2023-06-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='background_img',
        ),
    ]
